from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Awaitable, Callable, TYPE_CHECKING

if TYPE_CHECKING:
    from backend.websocket.context import WebSocketHandlerContext


EXPECTED_MESSAGE_TYPES = frozenset(
    {
        "directive",
        "select_template",
        "toggle_voice",
        "run_project",
        "stop_project",
        "get_notes",
        "read_note",
        "save_note",
        "delete_rule",
        "delete_architecture",
        "delete_decision",
        "get_rules",
        "get_planner_state",
        "get_ast_state",
        "list_projects",
        "create_project",
        "delete_project",
        "open_project",
        "save_project_file",
        "delete_project_file",
        "index_project",
        "find_references",
        "semantic_search",
        "create_coding_session",
        "apply_coding_session",
        "rollback_coding_session",
        "get_coding_session",
        "mission_list",
        "mission_create",
        "mission_delete",
        "mission_get",
        "mission_update",
        "mission_set_status",
        "work_package_create",
        "work_package_update",
        "work_package_set_status",
        "work_package_add_dependency",
        "deliverable_create",
        "deliverable_update",
        "deliverable_set_status",
        "evidence_attach",
        "criterion_create",
        "criterion_set_status",
        "mission_resume_snapshot",
        "mission_execute_work_package",
        "mission_apply_execution",
        "mission_review_execution",
        "mission_retry_execution",
        "mission_cancel_execution",
        "mission_release_stale_lock",
        "mission_autonomy_run",
        "mission_plan_decompose",
        "mission_checkpoint_create",
        "mission_checkpoint_restore",
        "mission_subdag_propose",
        "mission_subdag_get_history",
        "mission_plan_evaluate",
        "mission_adaptation_propose",
        "mission_adaptation_get_history",
        "mission_swarm_status",
        "mission_swarm_reassign",
        "mission_collaboration_status",
        "mission_collaboration_arbitrate",
        "mission_federation_status",
        "mission_federation_scale",
        "mission_federation_rebalance",
        "mission_federation_switch_mode",
        "mission_understanding_get",
        "mission_understanding_review",
        "mission_timeline_get",
        "start_lecture_recording",
        "stop_lecture_recording",
        "get_lecture_status",
        "list_lecture_history",
        "generate_lecture_lesson",
        "submit_lecture_quiz",
        "sentinel_get_status",
        "sentinel_run_audit",
        "sentinel_get_baseline",
        "sentinel_accept_known_good",
        "sentinel_get_actions",
        "sentinel_approve_action",
        "sentinel_reject_action",
        "sentinel_rollback_action",
        "sentinel_submit_review",
        "sentinel_get_shadow_telemetry",
        "mission_control_get",
        "mission_control_event_stream",
        "mission_control_command",
        "mission_intent_preview",
        "mission_intent_change",
        "mission_predict_impact",
        "mission_get_predictions",
        "mission_loop_status",
        "mission_loop_step",
        "mission_loop_run",
        "mission_loop_respond_human",
        "mission_decision_quality_status",
        "mission_policy_proposal_review",
        "mission_policy_rollback",
        "mission_experience_memory_status",
        "mission_experience_curate",
        "mission_semantic_graph_status",
        "mission_contract_discovery_status",
        "mission_contract_proposal_review",
        "mission_contract_health_status",
        "mission_contract_drift_review",
        "mission_contract_rollback",
        "mission_polymorphic_schema_status",
        "mission_polymorphic_variant_review",
        "mission_polymorphic_compatibility_check",
        "mission_contract_change_prediction",
        "mission_contract_migration_plan",
        "mission_contract_change_gate_action",
        "mission_build_contract_extraction_status",
        "mission_dynamic_consumer_resolution",
        "mission_build_contract_trigger_extract",
        "mission_behavioral_baseline_status",
        "mission_behavioral_proof_status",
        "mission_behavioral_proof_trigger",
        "mission_architecture_evolution_status",
        "mission_architecture_evolution_observe",
        "mission_architecture_evolution_evaluate",
        "mission_self_modification_status",
        "mission_self_modification_execute",
        "mission_self_modification_rollback",
        "mission_multi_agent_coordination_status",
        "mission_multi_agent_intent_submit",
        "mission_multi_agent_arbitrate",
        "mission_multi_agent_schedule",
        # Phase 67
        "mission_long_horizon_status",
        "mission_long_horizon_create",
        "mission_long_horizon_step",
        "mission_long_horizon_run",
        "mission_long_horizon_checkpoint_create",
        "mission_long_horizon_recover",
        "mission_long_horizon_adapt",
        "mission_long_horizon_completion_evaluate",
        # Phase 68
        "mission_quality_governance_status",
        "mission_quality_governance_snapshot",
        "mission_quality_governance_baseline",
        "mission_quality_governance_gate",
        "mission_quality_governance_debt_list",
        "mission_quality_governance_trend",
        "mission_quality_governance_hotspots",
        # Phase 69
        "mission_debt_remediation_status",
        "mission_debt_remediation_validate",
        "mission_debt_remediation_root_cause",
        "mission_debt_remediation_options",
        "mission_debt_remediation_plan",
        "mission_debt_remediation_execute",
        "mission_debt_remediation_resolve",
        # Phase 70
        "mission_release_readiness_status",
        "mission_release_readiness_baseline",
        "mission_release_readiness_evaluate",
        "mission_release_readiness_plan",
        "mission_release_readiness_gate",
        "mission_release_readiness_rollback",
        # Phase 71
        "mission_production_operations_status",
        "mission_production_operations_observe",
        "mission_production_operations_health",
        "mission_production_operations_slo",
        "mission_production_operations_remediate",
        "mission_production_operations_rollback",
        "mission_production_operations_replay",
        # Phase 72
        "mission_reliability_status",
        "mission_reliability_observe",
        "mission_reliability_anomalies",
        "mission_reliability_predict",
        "mission_reliability_plan",
        "mission_reliability_execute",
        "mission_reliability_replay",
    }
)


@dataclass(frozen=True, slots=True)
class HandlerResult:
    event_type: str
    payload: dict[str, Any]
    broadcast: bool = False

    def to_message(self) -> dict[str, Any]:
        return {"type": self.event_type, **self.payload}


MessageHandler = Callable[
    ["WebSocketHandlerContext", dict[str, Any]],
    Awaitable[HandlerResult | None],
]
