"""
JARVIS OS — Phase 61: Autonomous Test Synthesis & Coverage-Guided Validation
Module: contracts.py
Synthesizes contract tests covering required/optional fields, polymorphic variants (Phase 47),
closed exhaustive variants, and open fallback schemas.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from .candidate import TestCandidateManager
from .models import (
    CostEstimate,
    TestCandidate,
    TestFramework,
    TestRequirement,
    TestRequirementSource,
)
from .templates import TestCodeTemplates


class ContractTestGenerator:
    """Generates contract-oriented tests verifying schema adherence and polymorphic variants."""

    def __init__(self, candidate_mgr: TestCandidateManager) -> None:
        self.candidate_mgr = candidate_mgr
        self.templates = TestCodeTemplates()

    def generate_contract_suite(
        self,
        requirement: TestRequirement,
        contract_spec: Dict[str, Any],
        is_closed_exhaustive: bool = True,
    ) -> List[TestCandidate]:
        candidates: List[TestCandidate] = []
        cid = contract_spec.get("contract_id", requirement.contract_id or "Contract")
        module_path = requirement.file_id.replace("/", ".").replace(".py", "")

        variants = contract_spec.get("variants", ["default_variant"])

        # 1. Closed exhaustive generation: generate a test for each known variant
        for v in variants:
            payload = contract_spec.get("sample_payloads", {}).get(v, {"status": "ok", "variant": v})
            code = self.templates.render_python_contract(
                contract_name=cid,
                module_path=module_path,
                variant_name=v,
                payload=payload,
                is_polymorphic=len(variants) > 1,
            )
            cand = self.candidate_mgr.create_candidate(
                requirement_id=requirement.requirement_id,
                target=f"{cid}::{v}",
                framework=TestFramework.PYTEST,
                language="python",
                files=[requirement.file_id],
                inputs={"variant": v, "payload": payload},
                expected_outputs={"is_valid": True},
                invariants=[f"Variant '{v}' satisfies required fields"],
                code=code,
                risk=0.6,
                estimated_cost=CostEstimate(generation_cost=0.01, execution_cost=0.02, total_cost=0.03),
                predicted_coverage_gain=0.20,
                provenance="contract_test_generator",
            )
            candidates.append(cand)

        # 2. Open fallback generation: test behavior when unknown variant or partial payload is provided
        if not is_closed_exhaustive:
            fallback_payload = {"variant": "unknown_future_variant", "raw_data": {}}
            code_fb = f'''# Auto-generated by JARVIS Autonomous Test Synthesis (Phase 61)
# Open fallback test for contract {cid}
import pytest

def test_contract_{cid}_open_fallback():
    from {module_path} import validate_{cid}
    payload = {repr(fallback_payload)}
    is_valid, errors = validate_{cid}(payload)
    # Open fallback policy must either gracefully handle or return structured error
    assert is_valid or len(errors) > 0
'''
            cand_fb = self.candidate_mgr.create_candidate(
                requirement_id=requirement.requirement_id,
                target=f"{cid}::open_fallback",
                framework=TestFramework.PYTEST,
                language="python",
                files=[requirement.file_id],
                inputs={"payload": fallback_payload},
                expected_outputs={"graceful_fallback": True},
                invariants=[f"Contract '{cid}' safely falls back on unknown schema variant"],
                code=code_fb,
                risk=0.7,
                estimated_cost=CostEstimate(generation_cost=0.01, execution_cost=0.02, total_cost=0.03),
                predicted_coverage_gain=0.15,
                provenance="contract_test_generator_fallback",
            )
            candidates.append(cand_fb)

        return candidates
