import React, { useState } from 'react';
import {
  FlaskConical,
  ShieldCheck,
  CheckCircle2,
  XCircle,
  RotateCcw,
  Sparkles,
  Layers,
  Code2,
  Zap,
  Activity,
  Sliders,
  Terminal,
  FileCheck,
} from 'lucide-react';

interface TestRequirementView {
  id: string;
  source: string;
  symbol: string;
  risk: number;
  priority: number;
  invariant: string;
  scenario: string;
}

interface TestCandidateView {
  id: string;
  requirement_id: string;
  target: string;
  framework: string;
  language: string;
  risk: number;
  cost: number;
  cov_gain: number;
  status: 'ACCEPTED' | 'REJECTED' | 'RANKED' | 'GENERATED';
  code: string;
  rejection_reason?: string;
}

interface MutationView {
  id: string;
  type: string;
  target: string;
  detected: boolean;
  killer_test?: string;
}

export const AutonomousTestSynthesisPanel: React.FC = () => {
  const [activeSubTab, setActiveSubTab] = useState<
    'overview' | 'requirements' | 'candidates' | 'ranking' | 'coverage' | 'mutations' | 'regressions' | 'browser' | 'security'
  >('overview');

  const [selectedCandidateId, setSelectedCandidateId] = useState<string>('TEST_7b4c9e12');
  const [isSynthesizing, setIsSynthesizing] = useState<boolean>(false);
  const [filterStatus, setFilterStatus] = useState<string>('ALL');

  const [requirements] = useState<TestRequirementView[]>([
    {
      id: 'REQ_SYM_9a8b1c',
      source: 'SYMBOL_IMPACT',
      symbol: 'agents/payment.py::process_transaction',
      risk: 0.95,
      priority: 2.0,
      invariant: 'Transaction must adhere to idempotent execution and ledger clearance',
      scenario: 'unit',
    },
    {
      id: 'REQ_CTR_3f2e1d',
      source: 'CONTRACT',
      symbol: 'agents/payment.py::PaymentDTO',
      risk: 0.85,
      priority: 1.8,
      invariant: 'PaymentDTO must conform to polymorphic schema variants v1 and v2',
      scenario: 'contract',
    },
    {
      id: 'REQ_BEH_5c6d7e',
      source: 'BEHAVIORAL_INVARIANT',
      symbol: 'agents/payment.py::execute_behavioral_pipeline',
      risk: 0.90,
      priority: 1.9,
      invariant: 'Chain: REQUEST -> AUTH -> VALIDATION -> BUSINESS_LOGIC -> ECONOMIC_EFFECT',
      scenario: 'behavioral',
    },
    {
      id: 'REQ_CTX_404_drift',
      source: 'COUNTEREXAMPLE',
      symbol: 'agents/payment.py::process_transaction',
      risk: 0.95,
      priority: 2.0,
      invariant: 'Negative amount must be rejected without exception bypass',
      scenario: 'regression',
    },
    {
      id: 'REQ_BRO_nav_flow',
      source: 'USER_ACCEPTANCE_CRITERION',
      symbol: 'browser::mission_control_overview',
      risk: 0.70,
      priority: 1.5,
      invariant: 'Mission Control UI renders with zero console errors and valid selectors',
      scenario: 'browser',
    },
  ]);

  const [candidates] = useState<TestCandidateView[]>([
    {
      id: 'TEST_7b4c9e12',
      requirement_id: 'REQ_SYM_9a8b1c',
      target: 'agents/payment.py::process_transaction',
      framework: 'pytest',
      language: 'python',
      risk: 0.95,
      cost: 0.016,
      cov_gain: 0.15,
      status: 'ACCEPTED',
      code: `# Auto-generated by JARVIS Autonomous Test Synthesis (Phase 61)
import pytest
from agents.payment import process_transaction

def test_process_transaction_deterministic_unit():
    # Invariant: Transaction must adhere to idempotent execution
    result = process_transaction(amount=100.0, currency='EUR', user_id='usr_test_123')
    assert result is not None
    assert result.status == 'SUCCESS'
    assert result.cleared is True
`,
    },
    {
      id: 'TEST_8c5d0f34',
      requirement_id: 'REQ_CTR_3f2e1d',
      target: 'PaymentDTO::v2_polymorphic',
      framework: 'pytest',
      language: 'python',
      risk: 0.85,
      cost: 0.032,
      cov_gain: 0.25,
      status: 'ACCEPTED',
      code: `# Auto-generated by JARVIS Autonomous Test Synthesis (Phase 61)
import pytest
from agents.payment import validate_payment_contract

def test_contract_PaymentDTO_v2_polymorphic():
    payload = {'amount': 100.0, 'currency': 'EUR', 'variant': 'v2_polymorphic'}
    is_valid, errors = validate_payment_contract(payload)
    assert is_valid, f'Contract validation failed: {errors}'
    assert len(errors) == 0
`,
    },
    {
      id: 'TEST_9d6e1a56',
      requirement_id: 'REQ_CTX_404_drift',
      target: 'agents/payment.py::counterexample::cx_404_drift',
      framework: 'pytest',
      language: 'python',
      risk: 0.95,
      cost: 0.025,
      cov_gain: 0.20,
      status: 'ACCEPTED',
      code: `# Auto-generated by JARVIS Autonomous Test Synthesis (Phase 61)
# KNOWN_FAILURE_REGRESSION for counterexample: cx_404_drift
import pytest
from agents.payment import process_transaction

def test_regression_counterexample_cx_404_drift():
    # Verifies negative amount is strictly rejected
    with pytest.raises(ValueError):
        process_transaction(amount=-50.0, user_id='test')
`,
    },
    {
      id: 'TEST_bad_vacuous',
      requirement_id: 'REQ_SYM_9a8b1c',
      target: 'agents/payment.py::process_transaction',
      framework: 'pytest',
      language: 'python',
      risk: 0.50,
      cost: 0.005,
      cov_gain: 0.0,
      status: 'REJECTED',
      rejection_reason: "Trivial vacuous assertion detected: matched pattern 'assert True'",
      code: `def test_vacuous():
    assert True
`,
    },
  ]);

  const [mutants] = useState<MutationView[]>([
    { id: 'MUT_01', type: 'OPERATOR_SWAP (+ -> -)', target: 'process_transaction', detected: true, killer_test: 'TEST_7b4c9e12' },
    { id: 'MUT_02', type: 'CONSTANT_REPLACEMENT (True -> False)', target: 'process_transaction', detected: true, killer_test: 'TEST_7b4c9e12' },
    { id: 'MUT_03', type: 'CONDITION_INVERSION (< -> >=)', target: 'process_transaction', detected: true, killer_test: 'TEST_9d6e1a56' },
    { id: 'MUT_04', type: 'RETURN_VALUE_TAMPER (return None)', target: 'PaymentDTO', detected: true, killer_test: 'TEST_8c5d0f34' },
  ]);

  const coverageMetrics = {
    line: 0.92,
    branch: 0.88,
    symbol: 0.94,
    contract: 0.96,
    behavior: 0.91,
    invariant: 0.89,
    consumer: 0.84,
    browser: 0.78,
    composite: 0.895,
  };

  const handleSynthesize = () => {
    setIsSynthesizing(true);
    setTimeout(() => {
      setIsSynthesizing(false);
    }, 600);
  };

  const filteredCandidates = candidates.filter((c) => {
    if (filterStatus === 'ALL') return true;
    return c.status === filterStatus;
  });

  const selectedCandidate = candidates.find((c) => c.id === selectedCandidateId) || candidates[0];

  return (
    <div className="space-y-6" id="autonomous-test-synthesis-root">
      {/* Header & Global Decision Gate */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <span className="p-2 bg-indigo-500/10 text-indigo-400 rounded-lg border border-indigo-500/20">
              <FlaskConical className="w-5 h-5" />
            </span>
            <h2 className="text-xl font-bold text-white tracking-wide">
              Síntese Autónoma de Testes & Validação Guiada por Cobertura (Fase 61)
            </h2>
          </div>
          <p className="text-slate-400 text-sm max-w-2xl">
            Pipeline adaptativo de geração em malha fechada orientado por impacto em símbolos (Fase 60), contratos polimórficos (Fase 47), estágios de comportamento (Fase 50) e lacunas em 8 dimensões de cobertura.
          </p>
        </div>

        <div className="flex items-center gap-3 self-end md:self-center">
          <div className="px-3 py-1.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-semibold flex items-center gap-2">
            <ShieldCheck className="w-4 h-4" />
            AUTONOMOUS_TEST_SYNTHESIS_READY
          </div>
          <button
            onClick={handleSynthesize}
            disabled={isSynthesizing}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-sm font-medium transition-all shadow-lg flex items-center gap-2"
          >
            <RotateCcw className={`w-4 h-4 ${isSynthesizing ? 'animate-spin' : ''}`} />
            {isSynthesizing ? 'Sintetizando...' : 'Executar Síntese'}
          </button>
        </div>
      </div>

      {/* Navigation Subtabs */}
      <div className="flex border-b border-slate-800 overflow-x-auto gap-2 pb-1">
        {[
          { id: 'overview', label: 'Visão Geral & Métricas', icon: Activity },
          { id: 'requirements', label: 'Requisitos de Teste (5)', icon: Sliders },
          { id: 'candidates', label: 'Matriz de Candidatos', icon: Code2 },
          { id: 'ranking', label: 'Ranking por Risco', icon: Zap },
          { id: 'coverage', label: 'Cobertura 8D (89.5%)', icon: Layers },
          { id: 'mutations', label: 'Mutações Bounded (100%)', icon: Sparkles },
          { id: 'regressions', label: 'Regressões por Contraexemplo', icon: FileCheck },
          { id: 'browser', label: 'Playwright Scenarios', icon: Terminal },
          { id: 'security', label: 'Sentinel & Sandbox', icon: ShieldCheck },
        ].map((tab) => {
          const Icon = tab.icon;
          const active = activeSubTab === tab.id;
          return (
            <button
              key={tab.id}
              id={`tab-test-sub-${tab.id}`}
              onClick={() => setActiveSubTab(tab.id as any)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all whitespace-nowrap ${
                active
                  ? 'bg-indigo-600/15 text-indigo-400 border border-indigo-500/30'
                  : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800/50'
              }`}
            >
              <Icon className="w-4 h-4" />
              {tab.label}
            </button>
          );
        })}
      </div>

      {/* Subtab 1: Overview */}
      {activeSubTab === 'overview' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
              <span className="text-slate-400 text-xs font-semibold uppercase tracking-wider">Requisitos Mapeados</span>
              <div className="text-2xl font-bold text-white mt-1">5 Requisitos</div>
              <span className="text-emerald-400 text-xs mt-2 flex items-center gap-1">100% Cobertura de Impacto</span>
            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
              <span className="text-slate-400 text-xs font-semibold uppercase tracking-wider">Candidatos Sintetizados</span>
              <div className="text-2xl font-bold text-indigo-400 mt-1">4 Candidatos</div>
              <span className="text-slate-400 text-xs mt-2 flex items-center gap-1">3 Aceites | 1 Rejeitado</span>
            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
              <span className="text-slate-400 text-xs font-semibold uppercase tracking-wider">Cobertura Composta (8D)</span>
              <div className="text-2xl font-bold text-emerald-400 mt-1">89.5%</div>
              <span className="text-slate-400 text-xs mt-2 flex items-center gap-1">Meta Mínima: 75.0%</span>
            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
              <span className="text-slate-400 text-xs font-semibold uppercase tracking-wider">Escore de Mutações</span>
              <div className="text-2xl font-bold text-cyan-400 mt-1">100.0%</div>
              <span className="text-emerald-400 text-xs mt-2 flex items-center gap-1">4/4 Mutantes Mortos</span>
            </div>
          </div>

          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
            <h3 className="text-base font-bold text-white mb-3 flex items-center gap-2">
              <Layers className="w-4 h-4 text-indigo-400" />
              Arquitetura de Síntese em Malha Fechada
            </h3>
            <p className="text-slate-400 text-sm leading-relaxed mb-4">
              Ao invés de invocar LLMs de forma cega, o sintetizador conecta a análise de dependência de símbolos finos da Fase 60 a requisitos formais de teste, filtra testes triviais através do <code className="text-indigo-300">TestQualityEvaluator</code>, prioriza por risco multiobjetivo e executa em sandbox económico com ledgers sintéticos.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs text-slate-300">
              <div className="p-3 bg-slate-800/40 rounded-lg border border-slate-700/50">
                <div className="font-semibold text-white mb-1">Dual-Framework Detection</div>
                Suporte nativo a pytest (Python) e Vitest/Jest (TypeScript/JavaScript).
              </div>
              <div className="p-3 bg-slate-800/40 rounded-lg border border-slate-700/50">
                <div className="font-semibold text-white mb-1">Sandbox Económico Rígido</div>
                Garantia de mocks e fixtures sintéticos: nenhum teste toca em fundos reais.
              </div>
              <div className="p-3 bg-slate-800/40 rounded-lg border border-slate-700/50">
                <div className="font-semibold text-white mb-1">Imunidade a Vacuidade</div>
                Rejeição imediata de asserções inócuas como <code className="text-rose-300">assert True</code>.
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Subtab 2: Requirements */}
      {activeSubTab === 'requirements' && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
          <h3 className="text-base font-bold text-white mb-4">Matriz de Requisitos de Teste</h3>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm text-slate-300">
              <thead className="bg-slate-800/50 text-xs text-slate-400 uppercase">
                <tr>
                  <th className="p-3">ID Requisito</th>
                  <th className="p-3">Fonte</th>
                  <th className="p-3">Alvo (Símbolo / Contrato)</th>
                  <th className="p-3">Risco</th>
                  <th className="p-3">Prioridade</th>
                  <th className="p-3">Invariante Testado</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {requirements.map((req) => (
                  <tr key={req.id} className="hover:bg-slate-800/30">
                    <td className="p-3 font-mono text-xs text-indigo-400">{req.id}</td>
                    <td className="p-3">
                      <span className="px-2 py-0.5 rounded text-xs bg-slate-800 text-slate-300 border border-slate-700">
                        {req.source}
                      </span>
                    </td>
                    <td className="p-3 font-mono text-xs text-slate-200">{req.symbol}</td>
                    <td className="p-3">
                      <span className={`px-2 py-0.5 rounded text-xs font-semibold ${req.risk >= 0.9 ? 'bg-rose-500/20 text-rose-300' : 'bg-amber-500/20 text-amber-300'}`}>
                        {(req.risk * 100).toFixed(0)}%
                      </span>
                    </td>
                    <td className="p-3 font-semibold text-indigo-300">{req.priority.toFixed(1)}</td>
                    <td className="p-3 text-xs text-slate-400">{req.invariant}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Subtab 3: Candidates */}
      {activeSubTab === 'candidates' && (
        <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
          <div className="md:col-span-5 bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-bold text-white">Candidatos Sintetizados</h3>
              <div className="flex gap-1 text-xs">
                {['ALL', 'ACCEPTED', 'REJECTED'].map((st) => (
                  <button
                    key={st}
                    onClick={() => setFilterStatus(st)}
                    className={`px-2 py-1 rounded text-xs ${filterStatus === st ? 'bg-indigo-600 text-white' : 'bg-slate-800 text-slate-400'}`}
                  >
                    {st}
                  </button>
                ))}
              </div>
            </div>

            <div className="space-y-2">
              {filteredCandidates.map((cand) => (
                <div
                  key={cand.id}
                  onClick={() => setSelectedCandidateId(cand.id)}
                  className={`p-3 rounded-lg border cursor-pointer transition-all ${
                    selectedCandidateId === cand.id
                      ? 'bg-indigo-950/40 border-indigo-500/50'
                      : 'bg-slate-800/40 border-slate-700/50 hover:bg-slate-800/70'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-xs text-indigo-300 font-semibold">{cand.id}</span>
                    <span
                      className={`text-xs px-2 py-0.5 rounded font-medium flex items-center gap-1 ${
                        cand.status === 'ACCEPTED'
                          ? 'bg-emerald-500/20 text-emerald-300'
                          : 'bg-rose-500/20 text-rose-300'
                      }`}
                    >
                      {cand.status === 'ACCEPTED' ? <CheckCircle2 className="w-3 h-3" /> : <XCircle className="w-3 h-3" />}
                      {cand.status}
                    </span>
                  </div>
                  <div className="text-xs text-slate-300 font-mono mt-1 truncate">{cand.target}</div>
                  <div className="flex items-center gap-3 text-xs text-slate-400 mt-2">
                    <span>{cand.framework}</span>
                    <span>•</span>
                    <span>Custo: ${cand.cost.toFixed(3)}</span>
                    <span>•</span>
                    <span>Ganho: +{(cand.cov_gain * 100).toFixed(0)}%</span>
                  </div>
                  {cand.rejection_reason && (
                    <div className="text-xs text-rose-400 mt-2 bg-rose-950/30 p-2 rounded border border-rose-900/50">
                      {cand.rejection_reason}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          <div className="md:col-span-7 bg-slate-900 border border-slate-800 rounded-xl p-5 flex flex-col">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3 mb-3">
              <div>
                <span className="text-xs text-slate-400">Código do Teste Sintetizado</span>
                <div className="font-mono text-sm text-indigo-300 font-bold">{selectedCandidate.id}</div>
              </div>
              <span className="px-2 py-1 bg-slate-800 rounded text-xs text-slate-300 font-mono">
                {selectedCandidate.framework} ({selectedCandidate.language})
              </span>
            </div>
            <pre className="bg-slate-950 p-4 rounded-lg font-mono text-xs text-emerald-300 overflow-x-auto flex-1 border border-slate-800/80 leading-relaxed">
              {selectedCandidate.code}
            </pre>
          </div>
        </div>
      )}

      {/* Subtab 4: Ranking */}
      {activeSubTab === 'ranking' && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <Zap className="w-4 h-4 text-amber-400" />
              Ranking Multiobjetivo Guiado por Risco & Custo
            </h3>
            <span className="text-xs text-slate-400 font-mono">
              Score = w_risk*R + w_cov*Cov + w_impact*I - w_cost*C + SecurityBoost
            </span>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm text-slate-300">
              <thead className="bg-slate-800/50 text-xs text-slate-400 uppercase">
                <tr>
                  <th className="p-3">Posição</th>
                  <th className="p-3">Test ID</th>
                  <th className="p-3">Alvo</th>
                  <th className="p-3">Risco</th>
                  <th className="p-3">Ganho Previsto</th>
                  <th className="p-3">Custo Estimado</th>
                  <th className="p-3">Score Final</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {[
                  { rank: 1, id: 'TEST_9d6e1a56', target: 'counterexample::cx_404_drift', risk: 0.95, cov: 0.20, cost: 0.025, score: 2.842 },
                  { rank: 2, id: 'TEST_7b4c9e12', target: 'process_transaction', risk: 0.95, cov: 0.15, cost: 0.016, score: 2.785 },
                  { rank: 3, id: 'TEST_8c5d0f34', target: 'PaymentDTO::v2_polymorphic', risk: 0.85, cov: 0.25, cost: 0.032, score: 0.884 },
                  { rank: 4, id: 'TEST_bad_vacuous', target: 'process_transaction', risk: 0.50, cov: 0.00, cost: 0.005, score: 0.175 },
                ].map((item) => (
                  <tr key={item.id} className="hover:bg-slate-800/30">
                    <td className="p-3 font-bold text-amber-400">#{item.rank}</td>
                    <td className="p-3 font-mono text-xs text-indigo-300">{item.id}</td>
                    <td className="p-3 font-mono text-xs text-slate-200">{item.target}</td>
                    <td className="p-3">{(item.risk * 100).toFixed(0)}%</td>
                    <td className="p-3 text-emerald-400">+{(item.cov * 100).toFixed(0)}%</td>
                    <td className="p-3">${item.cost.toFixed(3)}</td>
                    <td className="p-3 font-mono font-bold text-indigo-400">{item.score.toFixed(3)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Subtab 5: Coverage 8D */}
      {activeSubTab === 'coverage' && (
        <div className="space-y-6">
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
            <h3 className="text-base font-bold text-white mb-2">Vetor de Cobertura Multidimensional (8D)</h3>
            <p className="text-slate-400 text-sm mb-6">
              Nenhuma dimensão isolada é tratada como prova suficiente. Cada alteração avalia 8 eixos ortogonais:
            </p>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              {[
                { name: 'Line Coverage', val: coverageMetrics.line, target: 0.85 },
                { name: 'Branch Coverage', val: coverageMetrics.branch, target: 0.80 },
                { name: 'Symbol Coverage', val: coverageMetrics.symbol, target: 0.90 },
                { name: 'Contract Coverage', val: coverageMetrics.contract, target: 0.95 },
                { name: 'Behavior Coverage', val: coverageMetrics.behavior, target: 0.90 },
                { name: 'Invariant Coverage', val: coverageMetrics.invariant, target: 0.85 },
                { name: 'Consumer Coverage', val: coverageMetrics.consumer, target: 0.80 },
                { name: 'Browser Coverage', val: coverageMetrics.browser, target: 0.70 },
              ].map((dim) => (
                <div key={dim.name} className="bg-slate-800/40 border border-slate-700/50 rounded-lg p-4">
                  <div className="flex justify-between text-xs text-slate-300 font-semibold mb-2">
                    <span>{dim.name}</span>
                    <span className={dim.val >= dim.target ? 'text-emerald-400' : 'text-amber-400'}>
                      {(dim.val * 100).toFixed(1)}%
                    </span>
                  </div>
                  <div className="w-full bg-slate-900 rounded-full h-2">
                    <div
                      className="bg-indigo-500 h-2 rounded-full transition-all"
                      style={{ width: `${dim.val * 100}%` }}
                    />
                  </div>
                  <div className="text-[10px] text-slate-400 mt-2">Meta: {(dim.target * 100).toFixed(0)}%</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Subtab 6: Mutations */}
      {activeSubTab === 'mutations' && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-base font-bold text-white flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-cyan-400" />
                Bounded Mutation Testing
              </h3>
              <p className="text-xs text-slate-400 mt-1">
                Mutações controladas aplicadas estritamente aos símbolos alterados para medir sensibilidade assértiva.
              </p>
            </div>
            <div className="px-3 py-1 bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-xs font-semibold rounded">
              Score: 100.0% (4/4 detectados)
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm text-slate-300">
              <thead className="bg-slate-800/50 text-xs text-slate-400 uppercase">
                <tr>
                  <th className="p-3">Mutante</th>
                  <th className="p-3">Operador Mutado</th>
                  <th className="p-3">Símbolo Alvo</th>
                  <th className="p-3">Status</th>
                  <th className="p-3">Teste Assassinador (Killer)</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {mutants.map((m) => (
                  <tr key={m.id} className="hover:bg-slate-800/30">
                    <td className="p-3 font-mono text-xs text-cyan-300">{m.id}</td>
                    <td className="p-3 text-xs">{m.type}</td>
                    <td className="p-3 font-mono text-xs text-slate-200">{m.target}</td>
                    <td className="p-3">
                      <span className="px-2 py-0.5 rounded text-xs bg-emerald-500/20 text-emerald-300 font-semibold">
                        DETECTADO (MORTO)
                      </span>
                    </td>
                    <td className="p-3 font-mono text-xs text-indigo-400">{m.killer_test}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Subtab 7: Regressions */}
      {activeSubTab === 'regressions' && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-4">
          <h3 className="text-base font-bold text-white flex items-center gap-2">
            <FileCheck className="w-4 h-4 text-emerald-400" />
            Regressões Derivadas de Contraexemplos (Fases 50–52)
          </h3>
          <p className="text-xs text-slate-400">
            Falhas comportamentais descobertas durante a prova formal são automaticamente convertidas em testes de regressão perpétuos sob a marcação <code className="text-emerald-300">KNOWN_FAILURE_REGRESSION</code>.
          </p>

          <div className="p-4 bg-slate-800/50 border border-slate-700/60 rounded-lg space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-mono text-xs text-emerald-400 font-semibold">
                KNOWN_FAILURE_REGRESSION::cx_404_drift
              </span>
              <span className="px-2 py-0.5 bg-emerald-500/20 text-emerald-300 text-xs rounded">ATIVO & VERIFICADO</span>
            </div>
            <div className="text-xs text-slate-300">
              <strong>Propriedade Violada:</strong> "Valores negativos de quantia devem gerar ValidationError e ser rejeitados antes da liquidação"
            </div>
            <div className="text-xs text-slate-400">
              <strong>Input Infrator:</strong> <code className="text-slate-300">amount=-50.0, bypass_auth=True</code>
            </div>
            <div className="text-xs text-slate-400">
              <strong>Prevenção:</strong> Teste <code className="text-indigo-300">TEST_9d6e1a56</code> integrado à suite padrão.
            </div>
          </div>
        </div>
      )}

      {/* Subtab 8: Browser */}
      {activeSubTab === 'browser' && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-4">
          <h3 className="text-base font-bold text-white flex items-center gap-2">
            <Terminal className="w-4 h-4 text-violet-400" />
            Síntese de Cenários Playwright para Browser
          </h3>
          <p className="text-xs text-slate-400">
            Para alterações frontend ou de missão integrada, o sintetizador gera fluxos Playwright com validação de seletores de DOM e invariante estrita de zero erros de consola e rede.
          </p>

          <div className="p-4 bg-slate-950 rounded-lg border border-slate-800 font-mono text-xs text-slate-300 space-y-1">
            <div className="text-slate-500"># Playwright Browser Flow — Mission Control Overview</div>
            <div>page.goto("http://localhost:5173/missions")</div>
            <div>await page.waitForSelector("#mission-control-root")</div>
            <div>await page.waitForSelector("#view-tab-autonomous_test_synthesis")</div>
            <div>expect(await page.locator("body").innerText()).toContain("Síntese Autónoma de Testes")</div>
          </div>
        </div>
      )}

      {/* Subtab 9: Security */}
      {activeSubTab === 'security' && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-4">
          <h3 className="text-base font-bold text-white flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            Test Security Sentinel & Sandbox Económico
          </h3>
          <p className="text-xs text-slate-400">
            O Security Sentinel é a autoridade máxima. Bloqueia preventivamente qualquer candidato que tente comandos arbitrários de sistema, vazamento de segredos, injeções ou evasão de sandbox.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-4 bg-slate-800/40 border border-slate-700/50 rounded-lg">
              <div className="text-xs font-semibold text-white mb-2">Comandos Destrutivos Bloqueados</div>
              <ul className="text-xs text-slate-400 space-y-1">
                <li>• <code className="text-rose-300">os.system / subprocess.Popen</code> (Bloqueado)</li>
                <li>• <code className="text-rose-300">shutil.rmtree / os.remove</code> (Bloqueado)</li>
                <li>• <code className="text-rose-300">eval() / exec()</code> (Bloqueado)</li>
              </ul>
            </div>
            <div className="p-4 bg-slate-800/40 border border-slate-700/50 rounded-lg">
              <div className="text-xs font-semibold text-white mb-2">Sandbox Económico</div>
              <ul className="text-xs text-slate-400 space-y-1">
                <li>• Ledgers sintéticos simulados em memória</li>
                <li>• 0 conexões com gateways financeiros reais</li>
                <li>• Mocks determinísticos de autenticação bancária</li>
              </ul>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
